version: '3.3'

services:
  web:
    build: ./
    command: gunicorn --bind 0.0.0.0:5000 app:app
    volumes:
      - ./:/usr/src/app/
      - templates:/usr/src/app/templates
      - static:/usr/src/app/templates/static

    ports:
      - "5000:5000"
    env_file:
      - ./.env.prod
    depends_on:
      - frontend
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app/frontend
      - templates:/usr/src/app/frontend/dist
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - templates:/usr/src/app/templates
    depends_on:
      - web

volumes:
  templates:
  static: